[general]
import = ["~/.config/alacritty/theme.toml"]

[window]
decorations = "None"
dynamic_title = false
opacity = 0.30
padding = { x = 3, y = 0 }

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"

[font.bold]
family = "RobotoMono Nerd Font"
style = "Bold"

[font.italic]
family = "RobotoMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "RobotoMono Nerd Font"
style = "Bold Italic"

[font]
size = 11
offset.x = 0  # For letter spacing (default: 0)
offset.y = 0  # For line spacing (default: 0)

[window.class]
general = "Alacritty"
instance = "Alacritty"

# [colors.primary]
# background = "#000000"
# foreground = "#e0e0e0"
#
# [colors.cursor]
# text = "#000000"
# cursor = "#ffffff"
#
# [colors.normal]
# black = "#1c1c1c"
# red = "#ff5555"
# green = "#50fa7b"
# yellow = "#f1fa8c"
# blue = "#61afef"
# magenta = "#ff79c6"
# cyan = "#8be9fd"
# white = "#bbbbbb"
#
# [colors.bright]
# black = "#555555"
# red = "#ff6e6e"
# green = "#69ff94"
# yellow = "#ffffa5"
# blue = "#7abaff"
# magenta = "#ff92df"
# cyan = "#a4ffff"
# white = "#ffffff"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
